

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.file.FileVisitResult;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.attribute.BasicFileAttributes;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ProgressMonitor;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author RiteshGaur (gaur.ritesh@gmail.com)
 */
public class DEFScreen extends javax.swing.JFrame {

    String directoryNametoScan;
    public static int dept;
    private final static String newline = "\n";
    private static int count = 0;
    ProgressMonitor progressMonitor;

    /**
     * Creates new form DEFScreen
     */
    public DEFScreen() {
        initComponents();
        dept = 5; //nested level for program to seach empty directory

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        DirToScan_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        dos5_radioBtn = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        dos10_radioBtn = new javax.swing.JRadioButton();
        dos20_radioBtn = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        Main_textArea = new javax.swing.JTextArea();
        Status_txtF = new javax.swing.JTextField();
        About_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delete Empty Folders ");
        setBackground(new java.awt.Color(153, 153, 255));
        setIconImage(getIconImage());
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setText("Directory to scan");

        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        DirToScan_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Network-Utility-icon - Copy.png"))); // NOI18N
        DirToScan_btn.setText("Click to choose directory");
        DirToScan_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirToScan_btnActionPerformed(evt);
            }
        });

        buttonGroup1.add(dos5_radioBtn);
        dos5_radioBtn.setSelected(true);
        dos5_radioBtn.setText("5");
        dos5_radioBtn.setBorderPainted(true);
        dos5_radioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dos5_radioBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Depth of scan");

        buttonGroup1.add(dos10_radioBtn);
        dos10_radioBtn.setText("10");
        dos10_radioBtn.setBorderPainted(true);
        dos10_radioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dos10_radioBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(dos20_radioBtn);
        dos20_radioBtn.setText("20");
        dos20_radioBtn.setBorderPainted(true);
        dos20_radioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dos20_radioBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dos5_radioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dos10_radioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dos20_radioBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dos5_radioBtn)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dos10_radioBtn)
                    .addComponent(dos20_radioBtn)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jInternalFrame1.setVisible(true);

        Main_textArea.setEditable(false);
        Main_textArea.setColumns(20);
        Main_textArea.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        Main_textArea.setLineWrap(true);
        Main_textArea.setRows(5);
        Main_textArea.setText("This program deletes all the empty folders/directories from the selected location. \n\nDepth of scan determines to search the nested directories. Such as if depth of scan value is 5, this program will search and delete 5 level of nested directories.\n\nAn example of 5 level of empty folders/directories.\n\nDir1\n |_Dir2\n      |-Dir3\n         |-Dir4\n             |-Dir5\n\nThis was written in few hours, hence this program is not very user friendly. I highly recommend you to use on “Download” directory. It is not recommended to scan any system directories. \n\n\n\n\n\nIf you want to test, create multiple empty folders on desktop and run this program (Choose your desktop in location) and see :) \n\nI personally has been using this, so far my mac is working fine. However, I do not take any responsibilities for any loss or damage of your data. Hence: This software is given 'as it is'!\n\n\n~Ritesh Gaur\n");
        jScrollPane1.setViewportView(Main_textArea);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        Status_txtF.setEditable(false);
        Status_txtF.setBackground(new java.awt.Color(238, 238, 238));
        Status_txtF.setText("Ready");
        Status_txtF.setBorder(null);

        About_btn.setText("About");
        About_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                About_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Status_txtF, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(About_btn)
                                .addGap(130, 130, 130)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DirToScan_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DirToScan_btn)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jInternalFrame1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Status_txtF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(About_btn))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DirToScan_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirToScan_btnActionPerformed
        count = 0;
        Status_txtF.setText("Ready....");
        Main_textArea.setText(" ");
        
        JFileChooser Fc = new JFileChooser();
        Fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = Fc.showOpenDialog(DEFScreen.this);
       
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            Status_txtF.setText("Scanning now....");
        
            JOptionPane.showMessageDialog(this,"\"Scanning the given location, this might take sometime. Program will not respond during the scan! \"");
           
            Main_textArea.setText(Fc.getSelectedFile().toString()); 
            
            directoryNametoScan = Fc.getSelectedFile().toString();
             
            Main_textArea.setText("Scanning directory: " + Fc.getSelectedFile().toString());
            
            ScanEmptyDir(directoryNametoScan);
            Status_txtF.setText("Finish Scanning...");
           
        }
    }//GEN-LAST:event_DirToScan_btnActionPerformed

    //dos5 = depth of scan =5
    private void dos5_radioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dos5_radioBtnActionPerformed
        // TODO add your handling code here:

       
        dept = 5;
       
    }//GEN-LAST:event_dos5_radioBtnActionPerformed

    //dos10 = depth of scan =10
    private void dos10_radioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dos10_radioBtnActionPerformed
        // TODO add your handling code here:
        
        dept = 10;
       
    }//GEN-LAST:event_dos10_radioBtnActionPerformed

    //dos20 = depth of scan =20
    private void dos20_radioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dos20_radioBtnActionPerformed
      
        dept = 20;
      
    }//GEN-LAST:event_dos20_radioBtnActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        count = 0;
        Status_txtF.setText("Scaning now.....");
        ScanEmptyDir(jTextField1.getText());
        Status_txtF.setText("Scaning finish!");
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void About_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_About_btnActionPerformed
   JOptionPane.showMessageDialog(this,"DeF, By Ritesh Gaur, Version 1.0");
          
    }//GEN-LAST:event_About_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DEFScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DEFScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DEFScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DEFScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DEFScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton About_btn;
    private javax.swing.JButton DirToScan_btn;
    public static javax.swing.JTextArea Main_textArea;
    public static javax.swing.JTextField Status_txtF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton dos10_radioBtn;
    private javax.swing.JRadioButton dos20_radioBtn;
    private javax.swing.JRadioButton dos5_radioBtn;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
//Method to scan empty directories    // End of variables declaration                   
//Method to scan empty directories    

    public static void ScanEmptyDir(String DIRname) {
        for (int i = 1; i <= dept; i++) {
            try {
                //Path startPath = Paths.get("c:/test");
               // jTextField2.setText("Scaning ......");
                Path startPath = Paths.get(DIRname);
                if (startPath.isAbsolute() == false) {                   // System.out.println(startPath.isAbsolute()); 
                    Main_textArea.setText("Location doesn't exsist");
                    i = 1;
                    break;

                }

                Files.walkFileTree(startPath, new SimpleFileVisitor<Path>() {
                    @Override
                    public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) throws IOException {
                        if (dir == null) {
                            Status_txtF.setText("Path is null..leaving now...");
                           // System.out.println("Path is null..leaving now...");
                            Main_textArea.setText("Path is null.. leaving now...");
                            System.exit(0);
                        }
                        removeFileAndParentsIfEmpty(dir);

                        return FileVisitResult.CONTINUE;
                    }

                    @Override
                    public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) {
                       // jTextField2.setText("Scaning ......");
                        Main_textArea.append(newline + "Directory Scanned : " + file.getParent());
                        return FileVisitResult.CONTINUE;
                    }

                    @Override
                    public FileVisitResult visitFileFailed(Path file, IOException e) {

                        return FileVisitResult.CONTINUE;
                    }
                });
            } catch (IOException e) {
            }
        }
        
       
       // jTextField2.setText("Scaning finish!");
        Main_textArea.append(newline + "DONE! -------- " + newline + count + " ------ empty directories are deleted!");
        
        JOptionPane.showMessageDialog(null, count + " Empty directories are found & deleted in depth of " + dept, "End of task", JOptionPane.INFORMATION_MESSAGE);
 
    }

    public static void removeFileAndParentsIfEmpty(Path path) throws IOException {

        if (path == null) {
            // System.out.println("Path ends with BASEPATH");
            return;
        }

        if (Files.isRegularFile(path)) {
            Files.deleteIfExists(path);
           // jTextArea3.append("Directory Deleted"+ Files.isDirectory(path.getFileName()));

        } else if (Files.isDirectory(path)) {

            try {
                // System.out.println("****File Deleted***: ");
                //jTextArea1.append(newline+Files.);
              // jTextArea3.append("Empty directory deleted"+ Files.isDirectory(path.getFileName()));
//                new SimpleThread(path).start();
//                SimpleThread.sleep(100);
               //jTextArea3.append("Directory Deleted"+ Files.isDirectory(path.getFileName()));
              
                Files.delete(path);
              
                count++;
                
               
            } catch (IOException e) {
                //  catch (DirectoryNotEmptyException e ) {
                // System.out.println("Dir not emplty" + Files.getFileStore(path)+ e);
              
                Main_textArea.append(newline + "************ DIR NOT EMPTY: " + path.getFileName());
                
                return;
            }

        }

        removeFileAndParentsIfEmpty(path.getParent());
    }

    public static String readKB() {
        InputStreamReader istream = new InputStreamReader(System.in);
        BufferedReader bufRead = new BufferedReader(istream);
        String inputval = null;
        try {
            inputval = bufRead.readLine();

        } catch (IOException err) {
            System.out.println("Error reading line");
        }
        return inputval;
    }
}



